name: Run the test suite


on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  Tests:

    strategy:
      fail-fast: false
      matrix:
        version: [ '3.8', '3.9', '3.10', '3.11' ]

    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - uses: actions/checkout@v3

      - name: Configure git
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip' # caching pip dependencies

      - name: Install pip
        run: python3 -m pip install --upgrade pip

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Install requirements
        run: find . -name requirements.txt | xargs -L 1 pip install -r

      - name: Run pytests
        run: python3 -m pytest
